# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly

  # Frontend dependencies (Svelte/Bun)
  - package-ecosystem: "bun"
    directory: "/frontend"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  # Backend dependencies (Rust)
  - package-ecosystem: "cargo"
    directory: "/backend"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
