# release-plz.toml

[workspace]
# Path to your git-cliff configuration file (for changelog generation).
# If you don't have one, `release-plz` will use a default.
# You can generate a default `cliff.toml` by running `git cliff --init`.
changelog_config = "cliff.toml"

# Enable updating the changelog. Defaults to true.
changelog_update = true

# Update dependencies with `cargo update` before release. Defaults to true.
dependencies_update = true

# Disable `release-plz` from creating the GitHub release.
# This is crucial when `cargo-dist` will handle the GitHub release.
git_release_enable = false

# Enable `release-plz` to create the git tag.
# This tag will trigger your `cargo-dist` workflow.
git_tag_enable = true

# Enable publishing to the cargo registry (crates.io by default). Defaults to true.
publish = false

# Run cargo-semver-checks to detect breaking changes. Defaults to true.
semver_check = true

# You can also configure specific packages within a workspace:
# [[package]]
# name = "your-package-name"
# changelog_update = false # Disable changelog for this specific package
