// Generated by ts-morph script. Do not edit manually!

import type { ReaperCommand, ReaperApiClient } from "../api";
import { ReaperScriptCommandBuilder } from './reaper-script-command-builder';

export class ReaperRpcClient {
	constructor(
		private readonly commandBuilder: ReaperScriptCommandBuilder, 
		private readonly apiClient: ReaperApiClient
	) { }

	public async listProjects(): Promise<{ projects: string[] }> {
		const commands: ReaperCommand[] = []; 
		commands.push(this.commandBuilder.setOperation("listProjects")); 
		commands.push(this.commandBuilder.getExtState("projects")); 
		const result = await this.apiClient.sendCommands(commands); 
		const projectsRaw = result[1];
		const projects = projectsRaw.split(',');
		return { projects }; 
	}

	public async openProject(projectPath: string): Promise<void> {
		const commands: ReaperCommand[] = []; 
		commands.push(this.commandBuilder.setExtState("projectPath", projectPath, true)); 
		commands.push(this.commandBuilder.setOperation("openProject")); 
		await this.apiClient.sendCommands(commands);
	}

	public async testActionId(testNonce: string): Promise<{ testOutput: string }> {
		const commands: ReaperCommand[] = []; 
		commands.push(this.commandBuilder.setExtState("testNonce", testNonce, true)); 
		commands.push(this.commandBuilder.setOperation("testActionId")); 
		commands.push(this.commandBuilder.getExtState("testOutput")); 
		const result = await this.apiClient.sendCommands(commands); 
		const testOutput = result[2];
		return { testOutput }; 
	}
}