// Generated by ts-morph script. Do not edit manually!

import type { ReaperCommand } from '../api';
import type { ReaperScriptCommandBuilder } from './reaper-script-command-builder';

export async function listProjects(): Promise<{ projects: string[] }> {
	const commands: ReaperCommand[] = [];
	const result = await listProjects();
	return { projects: result };
}

export async function openProject(projectPath): Promise<void> {
	const commands: ReaperCommand[] = [];
	const thing: ReaperScriptCommandBuilder;
	thing.getExtState();
	await openProject(projectPath);
}

export async function testActionId(testNonce): Promise<{ testOutput: string }> {
	const commands: ReaperCommand[] = [];

	const result = await testActionId(testNonce);
	return { testOutput: result };
}
