// Generated by ts-morph script. Do not edit manually!



export async function listProjects() {

	const result = await listProjects();

	return { then: result, catch: result, finally: result, __@toStringTag@74: result };

}

export async function openProject(projectPath: string) {

	await openProject(projectPath);

}

export async function testActionId(testNonce: string) {

	const result = await testActionId(testNonce);

	return { then: result, catch: result, finally: result, __@toStringTag@74: result };

}
