import { Target, type Argument } from './target';

export class TypeScriptTarget extends Target {
	constructor() {
		super();
		this.imports.push(
			`import type { ReaperCommand, ReaperApiClient } from "../api";`,
			`import { ReaperScriptCommandBuilder } from './reaper-script-command-builder';`
		);
	}

	override getOutputPathParts(): string[] {
		return ['..', 'frontend', 'src', 'lib', 'api', 'reaper-backend', 'reaper-rpc-client.ts'];
	}

	override renderHeader(): string[] {
		const lines = [`// Generated by ts-morph script. Do not edit manually!`];
		return lines;
	}

	override renderClassDefinition(): string[] {
		const constructorArgs = [
			`private readonly commandBuilder: ReaperScriptCommandBuilder`,
			`private readonly apiClient: ReaperApiClient`
		]
		return [
			`export class ReaperRpcClient {`,
			`\tconstructor(`,
			`\t\t${constructorArgs.join(', \n\t\t')}`,
			`\t) { }`
		];
	}

	override renderClassEnd(): string[] {
		return [`}`];
	}

	override renderOperations(): string[] {
		let code: string[] = [];
		let operationLines: string[][] = [];
		for (const { name, inputs, outputs } of this.operations) {
			operationLines.push(this.renderOperation(name, inputs, outputs));
		}
		code.push(operationLines.map((lines) => lines.join('\n')).join('\n\n'));
		return code;
	}

	private renderOperation(name: string, inputs: Argument[], outputs: Argument[]): string[] {
		const operationLines: string[] = [];
		let outputsStr;
		if (outputs.length === 0) {
			outputsStr = 'void';
		} else {
			outputsStr = `{ ${outputs.map((o) => `${o.name}: ${o.type.getText()}`).join(', ')} }`;
		}
		operationLines.push(
			`public async ${name}(${inputs
				.map((input) => `${input.name}: ${input.type.getText()}`)
				.join(', ')
			}): Promise<${outputsStr}> {`
		);
		operationLines.push(`\tconst commands: ReaperCommand[] = []; `);
		for (const { name, type } of inputs) {
			operationLines.push(`\tcommands.push(this.commandBuilder.setExtState("${name}", ${name}, true)); `);
		}

		operationLines.push(`\tcommands.push(this.commandBuilder.setOperation("${name}")); `);

		for (const { name, type } of outputs) {
			operationLines.push(`\tcommands.push(this.commandBuilder.getExtState("${name}")); `);
		}

		if (outputs.length === 0) {
			operationLines.push(`\tawait this.apiClient.sendCommands(commands);`);
		} else {
			operationLines.push(`\tconst result = await this.apiClient.sendCommands(commands); `);
		}

		for (let i = 0; i < outputs.length; i++) {
			const output = outputs[i]!;
			const resultIndex = i + inputs.length + 1; // +1 for the operation command
			if (output.type.isString()) {
				operationLines.push(`\tconst ${output.name} = result[${resultIndex}];`);
			} else if (output.type.isArray()) {
				operationLines.push(`\tconst ${output.name}Raw = result[${resultIndex}];`);
				operationLines.push(`\tconst ${output.name} = ${output.name}Raw.split(',');`);
			} else {

			}
		}

		if (outputs.length > 0) {
			operationLines.push(`\treturn { ${outputs.map((o) => o.name).join(', ')} }; `);
		}
		operationLines.push(`}`);
		return operationLines.map(x => `\t${x}`);
	}
}
