name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  # Detect changes to determine which jobs to run
  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      lua: ${{ steps.filter.outputs.lua }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
            lua:
              - 'lua/**'
            reapack:
              - 'reapack/**'

  # Job to build and test the SvelteKit Frontend
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.frontend == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # Or a specific version like '1.1.17'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: bun install --frozen-lockfile

      - name: Run frontend lint
        working-directory: ./frontend
        run: bun lint

      - name: Run frontend type check
        working-directory: ./frontend
        run: bun check

      - name: Run frontend tests
        working-directory: ./frontend
        run: bun test

      - name: Build frontend
        working-directory: ./frontend
        run: bun run build

  # Job to build and test the Lua Scripts
  lua:
    name: Lua
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.lua == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # Or a specific version like '1.1.17'

      - name: Install Lua and luacheck
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.4 luarocks
          sudo luarocks install luacheck

      - name: Run luacheck
        working-directory: ./lua
        run: luacheck .

      - name: Run Lua bundle
        working-directory: ./lua
        run: |
          ./bundle.sh
