name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Detect changes to determine which jobs to run
  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'

  # Job to build and test the SvelteKit Frontend
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.frontend == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # Or a specific version like '1.1.17'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: bun install --frozen-lockfile

      - name: Run frontend tests
        working-directory: ./frontend
        run: bun test

      - name: Build frontend
        working-directory: ./frontend
        run: bun run build

  # Job to build and test the Rust Backend
  backend:
    name: Backend
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.backend == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable # Recommended replacement
        with:
          components: clippy

      - name: Run cargo clippy
        working-directory: ./backend
        run: cargo clippy -- -D warnings

      - name: Run cargo tests
        working-directory: ./backend
        run: cargo test

      - name: Check release build
        working-directory: ./backend
        run: cargo check --release
