name: Github Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name for the release (e.g., v1.2.0)"
        required: true
        type: string
      release_notes:
        description: "Release notes for the release"
        required: false
        type: string
  workflow_call:
    inputs:
      tag_name:
        description: "Tag name for the release (e.g., v1.2.0)"
        required: true
        type: string
      release_notes:
        description: "Release notes for the release"
        required: false
        type: string

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Create ZIP Archive
        run: |
          mkdir -p reaper-setlist-${{ inputs.tag_name }}/reaper_www_root/reaper-setlist
          mkdir -p reaper-setlist-${{ inputs.tag_name }}/Scripts

          cp -r reapack/repo/reaper-setlist/files/setlist.html reaper-setlist-${{ inputs.tag_name }}/reaper_www_root/
          cp -r reapack/repo/reaper-setlist/files/reaper-setlist.lua reaper-setlist-${{ inputs.tag_name }}/Scripts/
          cp -r reapack/repo/reaper-setlist/files/reaper-setlist/* reaper-setlist-${{ inputs.tag_name }}/reaper_www_root/reaper-setlist/

          zip -r reaper-setlist-${{ inputs.tag_name }}.zip reaper-setlist-${{ inputs.tag_name }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag_name }}
          name: Release ${{ inputs.tag_name }}
          body: |
            ## Changes
            ${{ inputs.release_notes }}

            ## Download

            - `reaper-setlist-${{ inputs.tag_name }}.zip`

            Unpack and see the Installation.txt file for instructions.
          files: reaper-setlist-${{ inputs.tag_name }}.zip
          fail_on_unmatched_files: true
          draft: false
          prerelease: false
