# .github/workflows/docker-image.yml
name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  APP_NAME: reaper-setlist
  IMAGE_ID_RAW: ghcr.io/${{ github.repository }}

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install frontend dependencies
        run: bun install
      - name: Run frontend tests
        run: bun test

  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install Rust dependencies (and build for tests)
        run: cargo install --locked --path .
      - name: Run Clippy for linting
        run: cargo clippy --locked --all-features -- -D warnings
      - name: Run backend tests
        run: cargo test --locked --all-features

  build:
    runs-on: ubuntu-latest
    needs: [test-frontend, test-backend]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set lowercase IMAGE_ID for GHCR
        id: set_image_id
        run: |
          IMAGE_ID_LOWER=$(echo "${{ env.IMAGE_ID_RAW }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_ID=${IMAGE_ID_LOWER}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_ID }}
          tags: |
            type=raw,value=${{ env.APP_NAME }}-${{ github.sha }}
            type=ref,event=branch,enable=${{ github.ref == 'refs/heads/main' }},value=latest
            type=ref,event=pr,suffix=-pr{{ github.event.pull_request.number }}

      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.IMAGE_ID }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_ID }}:buildcache,mode=max
          target: final_image
          # Pass the Rust toolchain target as a build-arg based on TARGETPLATFORM
          # This is the crucial change for the Dockerfile
          build-args: |
            RUST_TOOLCHAIN_TARGET=${{ contains(github.event.pull_request.head.ref, 'arm64') || contains(github.event.ref, 'arm64') || contains(github.event.repository.default_branch, 'arm64') ? 'aarch64-unknown-linux-musl' : 'x86_64-unknown-linux-musl' }}
            # Wait, this logic is incorrect for multi-platform buildx.
            # buildx automatically sets TARGETPLATFORM and passes it to the Dockerfile.
            # We need to map TARGETPLATFORM within the Dockerfile to the RUST_TOOLCHAIN_TARGET.
            # So, the original Dockerfile's `RUN case` was correct.
