name: Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name for the release (e.g., v1.2.0)"
        required: true
        type: string
      version:
        description: "Version number for the release (e.g., 1.2.0)"
        required: true
        type: string
      release_notes:
        description: "Release notes for the release"
        required: false
        type: string
  workflow_call:
    inputs:
      tag_name:
        description: "Tag name for the release (e.g., v1.2.0)"
        required: true
        type: string
      version:
        description: "Version number for the release (e.g., 1.2.0)"
        required: true
        type: string
      release_notes:
        description: "Release notes for the release"
        required: false
        type: string

permissions:
  contents: write

jobs:
  build-and-package:
    name: Build and Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: bun install

      - name: Build frontend
        working-directory: ./frontend
        run: bun run build

      - name: Bundle Lua script
        working-directory: ./lua
        run: |
          luabundle main.lua -p *.lua -o reaper-setlist.lua

      - name: Prepare release package
        run: |
          mkdir -p package/web/setlist
          mkdir -p package/script

          # Copy frontend build output
          cp -r frontend/build/* package/web/

          # Copy Lua bundle
          cp lua/reaper-setlist.lua package/script/

          # Copy Installation.txt
          cp Installation.txt package/

          # Create the release archive
          cd package
          tar -czf ../reaper-setlist-${{ inputs.version }}.tar.gz .

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: reaper-setlist-package
          path: reaper-setlist-${{ inputs.version }}.tar.gz

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build-and-package
    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: reaper-setlist-package

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag_name }}
          name: Release ${{ inputs.tag_name }}
          body: |
            ## Changes
            ${{ inputs.release_notes }}

            ## Download

            - `reaper-setlist-${{ inputs.version }}.tar.gz`

            Unpack and see the Installation.txt file for instructions.
          files: reaper-setlist-${{ inputs.version }}.tar.gz
          fail_on_unmatched_files: true
          draft: false
          prerelease: false
